# Generated by Django 3.1.3 on 2021-11-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210606_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
